---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cup-image-fetch
  namespace: cup
spec:
  schedule: "*/30 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: cup-cron
          restartPolicy: Never
          volumes:
            - name: shared-vol
              persistentVolumeClaim:
                claimName: cup
          containers:
            - name: cluster-scanner
              image: alpine/k8s:1.36.1
              env:
                - name: EXCLUDE_IMAGES
                  value: "lscr.io/linuxserver/emby lscr.io/linuxserver/qbittorrent postgres alpine/k8s"
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - |
                  set -e

                  IMAGES_JSON=$(kubectl get pods --all-namespaces -o jsonpath='{.items[*].spec.containers[*].image}' \
                    | tr ' ' '\n' \
                    | sort -u \
                    | jq -R '.' \
                    | jq -s '.')

                  EXCLUDE_JSON=$(echo "$EXCLUDE_IMAGES" | tr ' ' '\n' | grep -v '^$' | jq -R '.' | jq -s '.')

                  NEW_JSON=$(jq -n \
                    --argjson extra_imgs "$IMAGES_JSON" \
                    --argjson exclude_imgs "$EXCLUDE_JSON" \
                    '{ 
                      "$schema": "https://raw.githubusercontent.com/sergi0g/cup/main/cup.schema.json",
                      "version": 3,
                      "socket": "none",
                      "images": {
                        "exclude": $exclude_imgs,
                        "extra": $extra_imgs
                      }
                    }')

                  TARGET_FILE="/config/cup.json"

                  if [ ! -f "$TARGET_FILE" ] || ! echo "$NEW_JSON" | cmp -s "$TARGET_FILE" -; then
                      echo "Changes detected or configuration missing. Updating $TARGET_FILE and restarting cup..."
                      echo "$NEW_JSON" > "$TARGET_FILE"
                      kubectl rollout restart deployment/cup -n cup
                  else
                      echo "No changes detected. Skipping cup restart."
                  fi

                  cat "$TARGET_FILE"
              volumeMounts:
                - name: shared-vol
                  mountPath: /config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cup
  namespace: cup
  labels:
    app: cup
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cup
  template:
    metadata:
      labels:
        app: cup
    spec:
      volumes:
        - name: shared-vol
          persistentVolumeClaim:
            claimName: cup
      containers:
        - name: cup
          image: ghcr.io/sergi0g/cup:v3.5.1
          command: ["/cup"]
          args: ["-c", "/config/cup.json", "serve", "-p", "8000"]
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: shared-vol
              mountPath: /config
---
apiVersion: v1
kind: Service
metadata:
  name: cup
  namespace: cup
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.255.140
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: cup