apiVersion: v1
kind: Namespace
metadata:
  name: cup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cup-cron
  namespace: cup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cup-cron
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    resourceNames: ["cup"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cup-cron
subjects:
  - kind: ServiceAccount
    name: cup-cron
    namespace: cup
roleRef:
  kind: ClusterRole
  name: cup-cron
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cup
  namespace: cup
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  storageClassName: local-path
---