apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mal-homepage
  namespace: homepage
spec:
  encryptedData:
    client-id: AgBvewWJZq4gJrl0oziGQea8bAxIIn4Haajc4RM9jHho1QU+GfTs+gey5SqkkMAqg4mM/4l8lE2e94yOz27HHU7un6+PFVsd4VGgkg4BsDLRqhgU7ZmMCFQkmx46rAI7U7Bj61NKmHKwHxaozNysSmMpWzw05VPoj2skZs8ZqLxP8bCm120HsRpMnqzyK4cjdJJ8itmXRuKpHF257Hvw5fjCD8uV83cPq5jyhmOobA7YPTr3kLae+Sd6DR/XLrG7PJ07wMQWpQYBjODeM8yFKnjFQbxVOvd7ldqcQT7l1cMBPg7n0wEAzSGhH/5NuhevVpGV0TOIrNlAr0gPEha5C5JU5iZKVDi9mJC2f4cNZLV1djNUQu/zuSt1W7o4Q0+XiJtwhH7Png9EfFCJR513DuCWkJkfNA7cUpnM0D7QChxHGxmKRo0awMjoRU+24t+FxvuyouMwaIYuWfx9hHJyPH2A/TA6lswa+vQTqUxRy6lQrsOn/V45QhgH7gBi40/84P+9q9jT+tYY/Xx3Z42m4C50P6wLClJbbyevOhqU1KtoSHM6M2jarPRL9WL5gZGu5x/jN4zT+BpMEJXfelZEW1PVyU7ICdFepL0QfX3xmLKLFTDqsq1Ik8JrscksBibPgVsG/xhgEqDu9iacNm8yGaaAWgTVLaN8Vb1mDj5frYxLGnnh4GIDj+TdakhEPPMv3Wp+jXMO7hjdFK7IGXMoenbbuX/Cb4SvrfIrHjC5t6dZGw==
  template:
    metadata:
      creationTimestamp: null
      name: mal-homepage
      namespace: homepage