apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy-l2
spec:
  externalIPs: true
  loadBalancerIPs: true
  interfaces:
    - ens18
  serviceSelector:
    matchLabels:
      loadbalancer: cilium
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
