ipam:
  mode: cluster-pool
  operator:
    clusterPoolIPv4PodCIDRList: 10.244.0.0/16
k8sServiceHost: 10.0.2.80
k8sServicePort: 6443
kubeProxyReplacement: true
operator:
  replicas: 1
envoy:
  enabled: false
serviceAccounts:
  cilium:
    name: cilium
  operator:
    name: cilium-operator
l2announcements:
  enabled: true