---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
data:
  guid: "3000"
  puid: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.122
  selector:
    app: qbittorrent
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8080

    - protocol: TCP
      port: 6881
      name: download
      targetPort: 6881

    - protocol: UDP
      port: 6881
      name: downloadudp
      targetPort: 6881
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: qbittorrent
  labels:
    app: qbittorrent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      volumes:
        - name: qbittorrentdata-vol
          persistentVolumeClaim:
            claimName: qbittorrent-pvc
        - name: qbittorrentconfig-vol
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:latest
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "8000Mi"
            cpu: "4000m"
        env:
        - name: GUID
          valueFrom:
            configMapKeyRef:
              name: qbittorrent-config
              key: guid
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: qbittorrent-config
              key: puid

        ports:
        - containerPort: 8080
        - containerPort: 6881

        volumeMounts:
          - mountPath: /downloads
            name: qbittorrentdata-vol
          - mountPath: /config
            name: qbittorrentconfig-vol