---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flood-truenas-pvc
  namespace: qbittorrent
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: flood
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: floodconfig-truenas-pvc
  namespace: qbittorrent
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: flood
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---