---
apiVersion: v1
kind: Namespace
metadata:
  name: qbittorrent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-truenas-pvc
  namespace: qbittorrent
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: qbittorrent
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrentconfig-truenas-pvc
  namespace: qbittorrent
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: qbittorrent
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---