---
apiVersion: v1
kind: Namespace
metadata:
  name: torrent
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
  namespace: torrent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: nfs-csi-ephemeral
---