apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: torrent
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:mh7OArn7GeCO7B4njDGNd4CrvmuAZo/2vobkTSl7CGgqALAWOL3jy89WQlM=,iv:uZwDCOcXE2ApKfiUO3ZGgLjRcjAFatpXZ0uTx6femPI=,tag:D95vH5ahG8P5XcHzVTHxKw==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:F4MeDOPmToYzVEzeP2/gH94lO0Gu0PWnljKyiCwBCw==,iv:zDAcEHjAOjNplfZ8UPoj24FbgWj6Jh8IGFVC4UZ1cfI=,tag:YuOJk43mJh2AHnDk3yyLdQ==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:aOV2xUM=,iv:me+th8g4Ijv0BmJUpWzlb/Q0qPADV8GJwp/QePuakiA=,tag:fkpLB4s931fJPXvyo6EeBg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd3pLTjFaaFNSS0Y4Y0tE
            NnI4UjBSL0YzbWpuMVBwaGNzRkkwU2xvajBnCjd6aDN0bmtQa243ZDZ6d2xCK1JE
            NlNiaFpEQXFuWGlHb3grRGQzOWs4Uk0KLS0tIFVDTDZxUGNxV01nRzB1bUJCSHNK
            MjM4ZE05ZmhaenBtRzhnTkxJT0RqVEEKI3S/1O1xV7Bp22epc9n4GCd3sL301hDD
            VAwSRwgDDX9HUDh/tFMbn6aBf8mwNiQ3m4OZ5HawpD+xWOQ2uHfKbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fcayjcsauny5czgwvyauqqqd4aa2kg3v7ghlvx6kjwqnz0luc9mq23famu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T13:26:48Z"
    mac: ENC[AES256_GCM,data:0FUf82B/ZxpuXPr1JjtaWtV5I2sw6aOyRCBBvP+RFa++hsCSGDQIyv94dRTsH9iN6vgvHwKDO66h8ITemAKjmygNxslchZdqChMQwlr+MFHBnpwx3e3wGS0Cm6UPB10upioS23C6/DqBFC5hD9MpDnkWyFOQeiZGLHvMBLPgBSE=,iv:4wDgXZkHlZr5x8J/LQalR4Tz17nTnoF6wYmVxTa2ZxA=,tag:2p5RURETALeja/SllZpuqw==,type:str]
    version: 3.13.1
