apiVersion: v1
kind: Secret
metadata:
    name: gluetun
    namespace: torrent
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:vy6Io/jB45Roux4Y4poK1mOpcWofd26gJVPRR2MdJ+dA7eTbz6OIcI0CFcE=,iv:XO83wRuw00KfHP/QV8U2pegOIH+jWw4/Gyg/IH5gc14=,tag:cAqposslzUiye/1e0goeQA==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:GrqX1uiWZMjT/USTc43HaClK2l5btfzRHvkaT2/yHg==,iv:G0ow9dxdQwBUl63/GHgZRbFxVB9U9+/5srk879YOYyg=,tag:lISD02veQOK1vdIjPZi6bA==,type:str]
    SERVER_COUNTRIES: ENC[AES256_GCM,data:AMT9B/U=,iv:zQw2OhZQfHkySmCB9k9V9gSS+WXJ2CLtOMIE172V59I=,tag:ktIyV3mE0gE/kYxv8WUlGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTmRXMUIrYW5SQ3BzeDZh
            SGUwdE84SXdJUlV2bkRaNCtpUzlIQ1ZoMUFJCnAxN01BZmFVcUZLdnUwSVVGZytE
            eTJxbHF4K29FVmtuVDh2bGc4RytHYzAKLS0tIHRURUlOQnd1UHpEUURuZGdmMCtW
            djVBYkNDREtzNHZmeFl1Ylp4UjkvKzAKHVhzh86Pnxs9Zt9NYwxus7Pacez82OFx
            kq7dFxHML8h1lqpuL79/fTG7yWCs9fZqthJQ/xYppj7PIPJsxEAS8g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T11:49:43Z"
    mac: ENC[AES256_GCM,data:YXtWDq7bTL16WhXsGuMd3v7BZQpNK4HMvkxTCHyJajD0rsOjCk4lvG6JXZorbQzhqAvB/3qY3Xzv7ywb9MGyqpGrMnrlKcdXMFEZ5IabQ4trjuaDOtCM2EPbwif59zJsr1kqa4pJ5K3tyBWwXYWhimrJM7fpfQLjM0tEN5wXSmo=,iv:+nM79Ea8++4W66NpC9ZyebDyQlrr8Odnt5nxDlEiCgU=,tag:luBKfXB761jcUkjkNEP7+Q==,type:str]
    version: 3.13.3
