---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recipes-config
  namespace: recipes
data:
  PUID: "3000"
  PGID: "3000"
  SECRET_KEY: recipes
  DB_ENGINE: "django.db.backends.postgresql"
  POSTGRES_HOST: "10.0.0.201"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: recipes
  POSTGRES_USER: recipes
  POSTGRES_PASSWORD: recipes
---
apiVersion: v1
kind: Service
metadata:
  name: recipes
  namespace: recipes
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.125
  ports:
  - port: 80
    targetPort: 8080
    name: http
  selector:
    app: recipes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipes
  namespace: recipes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipes
  template:
    metadata:
      labels:
        app: recipes
    spec:
      volumes:
        - name: recipes-vol
          persistentVolumeClaim:
            claimName: recipes-pvc
      containers:
      - name: recipes
        image: vabene1111/recipes:1.5.10
        ports:
          - containerPort: 8080
        volumeMounts:
          - mountPath: "/opt/recipes/mediafiles"
            name: recipes-vol
          - mountPath: "/config"
            name: recipes-vol
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: PGID
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: SECRET_KEY
        - name: DB_ENGINE
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: DB_ENGINE
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: POSTGRES_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: recipes-config
              key: POSTGRES_PASSWORD
---