---
apiVersion: v1
kind: Namespace
metadata:
  name: recipes
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-truenas-pvc
  namespace: recipes
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: recipes
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipespostgres-truenas-pvc
  namespace: recipes
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: postgres
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---