---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: recipes
  labels:
    loadbalancer: cilium
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.200
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: recipes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: recipespostgres-truenas-pvc
      containers:
      - name: postgres
        image: postgres:16
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-vol
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: recipes-secret
              key: POSTGRES_DB
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: recipes-secret
              key: POSTGRES_USER
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: recipes-secret
              key: POSTGRES_PASSWORD
              optional: false
---