---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mealie-config
  namespace: mealie
data:
  PUID: "3000"
  PGID: "3000"
  TZ: "Europe/Rome"
  TOKEN_TIME: "168"
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
  labels:
    loadbalancer: cilium
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.124
  ports:
  - port: 80
    targetPort: 9000
    name: http
  selector:
    app: mealie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      volumes:
        - name: mealie-vol
          persistentVolumeClaim:
            claimName: mealie-truenas-pvc
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v2.4.2
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: "/app/data"
            name: mealie-vol
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: mealie-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: mealie-config
              key: PGID
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: mealie-config
              key: TZ
        - name: TOKEN_TIME
          valueFrom:
            configMapKeyRef:
              name: mealie-config
              key: TOKEN_TIME
---