---
apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-truenas-pvc
  namespace: mealie
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: mealie
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealiepostgres-truenas-pvc
  namespace: mealie
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: postgres
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---