apiVersion: v1
kind: Secret
metadata:
    name: mealie
    namespace: mealie
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:EscJuzyrpUP3Na9SNu4ZljoTyjFu/Ouk0sIu75m0vfW1DbTX,iv:1gUd9DWwHiueAjtpB9usYRE9IS98bnqXWSpPmH9Njo0=,tag:dUSPmWd2ztvO0gBI259jEQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:+nTs+pLyyrKuoJYRd4G7fwr4JmFxZZ24CfxoGySjEUk=,iv:8QFVjIvTw58fRDg9llhrFZv6rFUHYmgzgyElPbx6VzY=,tag:WO/3LZccC6E1FislljCuqg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtLzJEVjUrZ1FZZWlNMlRG
            SDJFNUlSWWs1QmNqRnlHWGVtUFlEQjVyM0dnCnVkeW5GUzFlWkpRd0xxTlhpY1Rr
            RXpUM2F6MXoyTUs2eE12SDU1RmNXYU0KLS0tIDhhNkpBVHFmaWVSYlNEN3ZCajhS
            SC84SnBQZFRXRVNoVHUvTVFsaGFjM00KF2jW+YymXuB2W8OfJKeVC0GKgdKMRp2N
            izOyI7U+O6US2Lcre/hrm0oYR+RIA1IGP5M1AjMcfKGJHQFChiZJGA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T11:48:52Z"
    mac: ENC[AES256_GCM,data:CzJTYdRErO7B7yyrtfgSzwOQzeZ8rgf1078GnvDNS3eIt2Vsxm3tGQzixukxNiTGW5b7ByjM3qsN05AseeBFj0jy497+0uSl74B2FSU7z8/StIsNNL52TImuvyruH7HOFYhg9Hcn2mSMdxrZT3hyIFcLJQ+b9jIgqPBD2+Bm4TQ=,iv:5uAXd8QTVoYCkYMXjVQzKYyGTfb15UKhCur3881YcqM=,tag:6F0ensCmQBO7CgkvnPYqUw==,type:str]
    version: 3.13.3
