apiVersion: v1
kind: Secret
metadata:
    name: mealie
    namespace: mealie
type: Opaque
stringData:
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:cW7xdz/4dKfIF609omaqartpqRd+tNYR+RkZKi0O9d6mBKGw,iv:uL+0jSZL6Ri8SVf97KdzgkDw7XfJkpwXKhWU0WCnjR4=,tag:vYw7LYGg3SkLTg0aKfUQXQ==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:kEAqX1HNfFW0Mk5pNR5aaU4KcQv9U8rQvd9YmHYayEE=,iv:SdYYsdu4FZn6hyFpMlMS/dhfsW2Cok1dsnCVOgJF7QE=,tag:LtjfjF4rhO+AbW3IyuQUVQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDWE1TdjNrdTdGS0JzYzBv
            UjI0T0NoZUtsakYwMFdtZlZ5aFVNb0w3bkJVCnhXV0ZDSU9tcjBMOFZpbDd2ZVZv
            YWk4bmh2bERxNUUrUnEzYVRaaGN4ZVEKLS0tIEF3QW44YllQYXA2ZjZtR010YVZ3
            c2I2L043QnQ2VFpObkFHc05yeUxjUTgK2kIIC4BsS0jsgagW9TmlHMOrc4YIC3po
            8Og5u3BkY3Zo1wuOzqgX7QN1g+SExSq+SnPII3ZBXYgAEpDQ54IZ+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-19T15:00:20Z"
    mac: ENC[AES256_GCM,data:Z14K9RE8BSST45oJwe2tTiL6IHvzrEUlEexf4rVTRmrlp5GZOJ2GuSW9XfH4loeMUJxK5kUiM+badwYQ21D/j0nlRpFclXLx6vxauNsEN4+dM+nhN2sfLdE1QhRQz/+LrTXM7lc1e+guXOxxhkANc+/K40cYXhOAUfcl/7ESkpI=,iv:qEPwLrgh+fwuVyuempsP31qX8Za/a+wSd6+KaJdN44w=,tag:nO2iFGrfhFbh8x99+cdUQw==,type:str]
    version: 3.13.3
