---
apiVersion: v1
kind: Namespace
metadata:
  name: proxmox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-truenas-pvc
  namespace: proxmox
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: influxdb
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdbconfig-truenas-pvc
  namespace: proxmox
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: influxdb
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---