---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: proxmox
data:
  init_mode: "setup"
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: proxmox
  labels:
    loadbalancer: cilium
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.205
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 8086
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  namespace: proxmox
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      volumes:
        - name: influxdb-vol
          persistentVolumeClaim:
            claimName: influxdb-truenas-pvc
        - name: influxdbconfig-vol
          persistentVolumeClaim:
            claimName: influxdbconfig-truenas-pvc
      containers:
      - name: influxdb
        image: influxdb:2

        ports:
        - containerPort: 8086

        volumeMounts:
          - mountPath: /var/lib/influxdb2
            name: influxdb-vol
          - mountPath: /etc/influxdb2
            name: influxdbconfig-vol
---