---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rohan
  namespace: wiki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi-critical
---