apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: vault
type: Opaque
data:
    ADMIN_TOKEN: ENC[AES256_GCM,data:UzfkB2QDKb6Ch8bVHKNjujhfdnkaUC5cdMBkq28OAJjsrWGhovG4Q3DptYvzu8zy36Ck1De4PgonM/d4cF69gcSQWjDn7ip6mPDaO/wG6lvt1rWlWYYlnC4pOGjd1YC7WczQ4RH23xYbO2N2nVvBwaGsC/Qzag==,iv:rLZDO7ekR0CPKWFqthYvpeYMuBU7tqdW2tjut7Cxe/g=,tag:BNgyU5IjE+JdBKUXrI3hgw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5T2pzSUkvV0NHQWhDYUFR
            SytxaHVqOW0zLy9iZ0xRa0pIUE5Fd0pxbWhZCmlCV3pqSHV5bEVJTnBCTk5WUXI1
            Rzc1elVQUktBYWphTXpDZXZkQjlTWnMKLS0tIHhZbk8vODhwTDgzUVpyeVE4ZUlE
            Ujc5YWNhS0RVeHQ1TTFEYzVUUlY2ekUKvBnozIIaSXj46AExRxbAX1IGsvZx7CcA
            LRqmMdK1EdmPf40SI/3r6P+j4KDyIM5HXAT9ASVJH8emBVaNwND8oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T11:49:43Z"
    mac: ENC[AES256_GCM,data:PuoAsBeLHU2HGMhV7fhxCYcMQQ32Cnggo+gIDTvRCvrMtrI0v5T1AeDKnrufjSij241xXXi3mfCN2vtQBFd3MuhOD1nsbuEc89rUlOiAWyH5nw8+HVqD+2qTo4Hif54qWPY3cLeDvsE5MSNrf3pWeK81aW+V+pUvlLa5EtTCl6Y=,iv:2MebfCzWvIwwKcBrOF8ivNJ0RsTecSuah8R/4srV148=,tag:i5SM/JVrJ779pTviZzqfbA==,type:str]
    version: 3.13.3
