---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
  namespace: gitea
data:
  guid: "3000"
  puid: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.121
  selector:
    app: gitea
  ports:
    - protocol: TCP
      port: 80
      name: http
      targetPort: 3000

    - protocol: TCP
      port: 22
      name: ssh
      targetPort: 2222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: giteadata-vol
          persistentVolumeClaim:
            claimName: giteadata-local-pvc
        - name: giteaconfig-vol
          persistentVolumeClaim:
            claimName: giteaconfig-local-pvc
      containers:
      - name: gitea
        image: gitea/gitea:1.21.1-rootless
        resources:
          requests:
            memory: "125Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "1000m"
        env:
        - name: GUID
          valueFrom:
            configMapKeyRef:
              name: gitea-config
              key: guid
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: gitea-config
              key: puid

        ports:
        - containerPort: 3000
        - containerPort: 2222

        volumeMounts:
          - mountPath: /var/lib/gitea
            name: giteadata-vol
          - mountPath: /etc/gitea
            name: giteaconfig-vol