---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: giteaconfig-truenas-pvc
  namespace: gitea
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: gitea
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: giteadata-truenas-pvc
  namespace: gitea
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: gitea
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---