---
apiVersion: v1
kind: Namespace
metadata:
  name: git
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea
  namespace: git
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-csi-critical
---