---
apiVersion: v1
kind: Namespace
metadata:
  name: emby
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-truenas-pvc
  namespace: emby
  labels:
    app: emby
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embymedia-truenas-pvc
  namespace: emby
  labels:
    app: emby
spec:
  storageClassName: nfs-csi
  volumeName: pvc-51f7c0cb-8ad7-44c3-a065-b3d283c2da99
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
---