---
apiVersion: v1
kind: Namespace
metadata:
  name: emby
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emby-local-pvc
  namespace: emby
  labels:
    app: emby
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: embymedia-local-pvc
  namespace: emby
  labels:
    app: emby
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---