---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-truenas-pvc
  namespace: homeassistant
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: homeassistant
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---