apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
        config.cupdate/ignore: "true"
    spec:
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
      containers:
      - name: valkey
        image: docker.io/valkey/valkey:9.1-alpine
        args: ["--save", '""', "--maxmemory", "200mb", "--maxmemory-policy", "noeviction"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 50m
            memory: 64M
          limits:
            cpu: 250m
            memory: 300M
        startupProbe:
          exec:
            command:
              - valkey-cli
              - ping
          initialDelaySeconds: 3
          periodSeconds: 3
          failureThreshold: 5
        livenessProbe:
          exec:
            command:
              - valkey-cli
              - ping
          periodSeconds: 10
          timeoutSeconds: 3
        ports:
          - containerPort: 6379
            name: valkey
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: docs
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: valkey
    name: tcp
  selector:
    app: valkey