---
apiVersion: v1
kind: Namespace
metadata:
  name: technitium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-truenas-pvc
  namespace: technitium
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: technitium
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
---