apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: docs
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:ealOlTAXH6C6BEnj7vYuWWxVYrTQIi9ohjJhjH+8+VJ4Icv+A3cVXIdX3h6uicydT0Z/yKAPl/8Mibu7gcLQJN79VdsSL8hw4IN+uiUYemaZThYMtP4=,iv:V8EzefAe2JFOY1RzCBcEe8WjuoP77B3WrwiSnRs/21s=,tag:vvWuriTx8J6elrsG3wnaww==,type:str]
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:vcLugkpiseG6YfAUfmxwQVStKPyMzE93qBbbDBkuHrxEoROtwYMtnYBW1s0tPxBVE+Y/KUpsBbmkHlRxVfpk5kI8mGdThT/y5mEvj6KNSzAwsumBrDP/jjNyoxRR9fk0zZaHCS5LIGhgr24iMRhGTrAnj7rM466IFLHO8xGRVwS6mZkJClbNYGpFxAX78uiS+hTaAtDDF+9owEVvsgdCuLqU5+ZvwtQiIDOgnkQfpKX56Ab9NgtF6tYk3Y626GkLZsrnQpfF9GrIWK2Y4tYeVkI17siKmTfkzDdZESdojFt0+PjG/oA0BDwvivr55FYky6Y4IHCc+NZKN210UEWeHahntZTjlrkjNL13pCGHefeOmEbMTEpvUsCZ0w25r7GWyMVF1Qg=,iv:uaWJJw7mMcbe3gNaWaNXjJrkf2xNrQJcEvkXx44rQf4=,tag:gllwgXeWWcLMJmrTsj+oCQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WXE3YllOYmpxZnMxL2hk
            VjVhZWZDUnJFcFpZV1NMTlBCejhRaEdQbVE4CmxQOFRoWDVxRFZROVNOcE5haTJz
            NS95d3grK0tGWU1rWjdSMWt5bWx5alEKLS0tIFdoc3MvZ1p1cmlyZlJPSlU2L2lX
            VWM4d0VpUHVLc2VZUmpBaXdWSnRMRkkK+Vv+je2dJQi0dd8kSrJemEk7s1dkrNeP
            StAQ92f7YLCNuUJROhy4Ah2qqznptHwz6C3qGQBqrWQiOk9VTGdIyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T11:49:43Z"
    mac: ENC[AES256_GCM,data:Tkqp/qdIAa8Tf3gNquxUspieIZGP8EJ14yKheTcC/AZOE4C5W0oHUOwA469lItdTWUMGbEYa3LLpXPMNa0kcStSAnL2yfkOWFPNn1gVmgy5SOVHYX9BGWqQF4OgAMGSSB9DxHqiLwbvrRrdRxS/ITsArYRtWf3xog0x+QAQx7qs=,iv:TjYg3PKt9GcgsCxF9L2ctFegHCuxRSgzyFSWETUuZ80=,tag:mVqlWs1TQ7Vxlz+CyzsSHw==,type:str]
    version: 3.13.3
