apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: docs
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:PHUSDDp6gderfaUobI2aJ38NgR11667mDbhsOTF4QVbxrS+a5ujH8pNvrZnCKrac4+vwLyfWVD9VUhRKAEdEgnWrPS4WxtHrWyniQx0OgRZZwUseNb4=,iv:qK/w3+nRzvXmus/RvyMQXXLIhtuKFtE3M3mcfpt+tG0=,tag:HjyELZz4uwnVKd1Pg6Biyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUXJjV3AvcHNUTnU4TTZR
            OCtOWlYzVEoxckhKOUFpaFAzWXBTRnU0SFRvCkhTK1BNUytYUDlQMFNLampMQ2g3
            NlpiY01EVHZtM0pYWGFldUhSdHA3Y0kKLS0tIG9lWnhNYlU4QnRqKzhRVUNKNW0v
            QUtQZERRMUxsM3B6UDFGL3IwKzVtNW8K++SNH1W2eieIvN3V19XWmoK1cD2gdErn
            YhtrAlorJbeL8hj9AkclltR14F5ZYrSsog1jWkz0+8SgzgXoFeT2lQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fcayjcsauny5czgwvyauqqqd4aa2kg3v7ghlvx6kjwqnz0luc9mq23famu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-28T14:47:25Z"
    mac: ENC[AES256_GCM,data:Ou6AVGWGNe7+h9yENBpN7Jq4PgmQvLwk/pz4fyq2X0sGl+csiuMpdeuvyc8cixkfTZtiswp4z9YmFdZdwWv3xp1PKErMGZ/GK533Kn7c8H2uVFxwYLEJ1QKVa+p2tf3fWBZ6z3+TwtSERlhiSn+Ox7Uu2c9xYHlZBV+umRJxtiY=,iv:OzSSpYjgodseeg+z6/MhisVfm3BI8/AoN6WVe7JTDCI=,tag:vWjGVot4RxZtnbOms4ug6A==,type:str]
    version: 3.13.2
