---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-csi-critical
---