---
apiVersion: v1
kind: ConfigMap
metadata:
  name: speedtest-config
  namespace: speedtest
data:
  PUID: "1000"
  PGID: "1000"
  DB_CONNECTION: pgsql
  DB_HOST: "10.0.0.200"
  DB_PORT: "5432"
  DB_DATABASE: speedtest
  DB_USERNAME: speedtest
  DB_PASSWORD: 09xb *&!BXAS897d1@
---
apiVersion: v1
kind: Service
metadata:
  name: speedtest
  namespace: speedtest
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.124
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: speedtest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      volumes:
        - name: speedtest-vol
          persistentVolumeClaim:
            claimName: speedtest-local-pvc
      containers:
      - name: speedtest
        image: ghcr.io/alexjustesen/speedtest-tracker:v0.15.2
        ports:
          - containerPort: 80
          - containerPort: 443
        volumeMounts:
          - mountPath: "/config"
            name: speedtest-vol
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: PUID
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: PGID
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: DB_CONNECTION
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: DB_PORT
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: DB_DATABASE
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: speedtest-config
              key: DB_PASSWORD
---