---
apiVersion: v1
kind: Namespace
metadata:
  name: speedtest
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-postgres-local-pv
  labels:
    app: postgres
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/sushi/local-storage/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - it-sushi-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: speedtest-local-pv
  labels:
    app: speedtest
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /home/sushi/local-storage/speedtest
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - it-sushi-1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-postgres-local-pvc
  namespace: speedtest
  labels:
    app: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
  selector:
    matchLabels:
      app: postgres
  storageClassName: local-storage 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest-local-pvc
  namespace: speedtest
  labels:
    app: speedtest
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi 
  selector:
    matchLabels:
      app: speedtest
  storageClassName: local-storage 
---