---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: speedtest
data:
  POSTGRES_DB: speedtest
  POSTGRES_USER: speedtest
  POSTGRES_PASSWORD: 09xb *&!BXAS897d1@
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: speedtest
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.200
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: speedtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: speedtest-postgres-local-pvc
      containers:
      - name: postgres
        image: postgres:16
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-vol
        env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_PASSWORD
---