---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-truenas-pvc
  namespace: grafana
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: grafana
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---