---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: immich
data:
  POSTGRES_EXTENSIONS: cube, earthdistance, vectors
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: immich
  labels:
    loadbalancer: cilium
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.201
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: immich
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: postgres-vol
          persistentVolumeClaim:
            claimName: immichpostgres-truenas-pvc
      containers:
      - name: postgres
        image: tensorchord/pgvecto-rs:pg14-v0.3.0
        ports:
          - containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-vol
        env:
        - name: POSTGRES_EXTENSIONS
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_EXTENSIONS
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
              optional: false
---