env:
  REDIS_HOSTNAME: 10.0.0.203
  REDIS_PORT: 6379
  DB_HOSTNAME: 10.0.0.201
  DB_USERNAME: "immich"
  DB_DATABASE_NAME: "immich"
  DB_PASSWORD: "replacewithpasswordfromsecret"
  IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
  UPLOAD_LOCATION: "./library"

image:
  tag: v1.116.2

immich:
  metrics:
    enabled: false
  persistence:
    library:
      existingClaim: immich-truenas-pvc
  configuration: {}

# ---Immich components---

server:
  enabled: true
  image:
    repository: ghcr.io/immich-app/immich-server
    pullPolicy: IfNotPresent
  ingress:
    main:
      enabled: false
      annotations:
        # proxy-body-size is set to 0 to remove the body limit on file uploads
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
      hosts:
        - host: immich.local
          paths:
            - path: "/"
      tls: []

machine-learning:
  enabled: false
  image:
    repository: ghcr.io/immich-app/immich-machine-learning
    pullPolicy: IfNotPresent
  env:
    TRANSFORMERS_CACHE: /cache
  persistence:
    cache:
      enabled: true
      size: 10Gi
      type: emptyDir
      accessMode: ReadWriteMany

# ---Dependencies---

postgresql:
  enabled: false
  image:
    repository: tensorchord/pgvecto-rs
    tag: pg14-v0.3.0
  global:
    postgresql:
      auth:
        username: immich
        database: immich
        password: immich
  primary:
    initdb:
      scripts:
        create-extensions.sql: |
          CREATE EXTENSION cube;
          CREATE EXTENSION earthdistance;
          CREATE EXTENSION vectors;

redis:
  enabled: false
  architecture: standalone
  auth:
    enabled: false
