image:
    baseRepo: registry.k8s.io
    nfs:
        repository: registry.k8s.io/sig-storage/nfsplugin
        tag: v4.13.4
        pullPolicy: IfNotPresent
    csiProvisioner:
        repository: /sig-storage/csi-provisioner
        tag: v6.3.0
        pullPolicy: IfNotPresent
    csiResizer:
        repository: /sig-storage/csi-resizer
        tag: v2.2.1
        pullPolicy: IfNotPresent
    csiSnapshotter:
        repository: /sig-storage/csi-snapshotter
        tag: v8.6.0
        pullPolicy: IfNotPresent
    livenessProbe:
        repository: /sig-storage/livenessprobe
        tag: v2.19.0
        pullPolicy: IfNotPresent
    nodeDriverRegistrar:
        repository: /sig-storage/csi-node-driver-registrar
        tag: v2.17.0
        pullPolicy: IfNotPresent
    externalSnapshotter:
        repository: /sig-storage/snapshot-controller
        tag: v8.6.0
        pullPolicy: IfNotPresent