---
apiVersion: v1
kind: Namespace
metadata:
  name: kitchenowl
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kitchenowl-truenas-pvc
  namespace: kitchenowl
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: kitchenowl
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---