---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couchdb-truenas-pvc
  namespace: obsidian
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: couchdb
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---