---
apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-truenas-pvc
  namespace: minecraft
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: minecraft
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraftmysql-truenas-pvc
  namespace: minecraft
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: minecraft
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---