---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minecraft-secret
  namespace: minecraft
spec:
  encryptedData:
    MYSQL_PASSWORD: AgAOkIyOfDBpysBoh9DtZXVUDAaOu68ss1F8EoyY8b2DT+jLeFNnFxTMALXcGbuaUAGE6Y1BN3PMl1GQbOgqVazxenzTr8i81PdUhSVnSyX7FU/ZNnEWNCjMOvqQ15Za82Kl49vW2Rl3Ym9dWlEfwNpytfv640t/hHQ02JFWUDp4T8HGf5mUg/baPPzQyksWSqTvctyFF3drb7SbfifBUTTpKSV6TDnzJMKo/1Jo4cWNjzN8g21RxVNQzxigf3pMPLmGyUNbJmXXoL2YZ+Z9jPkvhe4yL7O07FQeAi/G/PwFaaZVxBCmgfDGmFd1KzQUsNoJl8bIOSxlXfiT+U+i9Hr/DVLuR6MhY2UUA/31+tsl4RTt0hzYX6y5k2TqbSGZjJr8WfruQD0H+Qp0pB6Kqzn4UrN7l0LE0rV7PaMkO+ZI8Yn64LuQQokCxCfS6/On3DkmYIggV8THcUQjFIMNx7HYKFk0KWKHk7Kc3RmmBwtlHNENIcKTr5Up3owLwQ5cmAmEZzfJawHigHrSodFaptWu8wScnaK4zy168IHKBjQcTpw54wNTs80tGKi/BM9Vdn0P7hOcaWkJAXdHPrrSJjBjVD4ZPZO6ue9sozvqhJ1dNbsvCo0MHuDX/vGm9W0g2nqg6ydSRu79qesWGX85oINXxm/Ups0Rh3ZJTtsWyMbMue47h/CZ8OW+mIHQQ/UPX9QIGr9MB3hHqjb04B7VfCrume8=
    MYSQL_ROOT_PASSWORD: AgCSKs1dXgZjp8rWIrbVfKEIGu5eOizxD0oxYWMHChc6tcMLYxm/KBENeyVrv+U23SgY0XClYtlSbqCBzjS/RHWegmifbZu5ZoEOfavlrCOaBjLq8aso+UHdWX4CbJ53fzHmJo8HwBwRYkqzYCLRrvT8Vz3HJq7vdwKRPNGOsvQUZkYUTA8ROIyA1DrI7+ISD6cI5bHaQ7G0TgKilBEkcUUveqAll4NvfCMLGFFJXxj6czG2kfBHtQZlRD5DRHtFpcDP8djk3J8Nw3VAekRCOG2KeqmT6Ay+TghJALd9jQFYLSTy222Whw/5KCmAICfWqPiv4a53+bY7/ggIctMYHCVQ01ccBgHvKK+YDWfpG6X75ehDV5itXALnviweWICj+nqStwy6mLzdFxYRGlG7EfCj2fxFaPPZlxDr39ZlJ1H3n2FF7NyZaCmjwC3zJbsvhvjxtFDVC+DkoU0yxrcG6oiRzBbU/bASCBCniOvACevSKxiUYCGF0ZHtIAnPsyxCPXmDIqfWF+YDWv6SBzBMSHe+7sKcaJ7snJqlYtMdU4qCbRe4SbeMvjNF0rKbABk5mgdFNajXCbkNd1V6Gucauxokz7MA4gXAG/nUlTyrXgyNXsoU1Iky4AyAi35ginKvTi3pWmVaZAxDUaeYP4bbwlfkdScWhh2sx30hORI54CzdAqWF+13ZLqhRP9J1ymD8mfcYV89lpnieyHk=
  template:
    metadata:
      creationTimestamp: null
      name: minecraft-secret
      namespace: minecraft
    type: Opaque
---