---
apiVersion: v1
kind: Namespace
metadata:
  name: memos
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memo
  namespace: memo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi-critical
---