---
apiVersion: v1
kind: Namespace
metadata:
  name: copyparty
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: copyparty
  namespace: copyparty
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 250Gi
  storageClassName: nfs-csi-critical
---