apiVersion: v1
kind: Secret
metadata:
    name: postgres
    namespace: immich
type: Opaque
data:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:f/l9WB72qKlRtNGN5Z/W5CLTRsMBvjIDCLKR/WUP,iv:ajS/IM94sJG0iZ/nJC6o7dWEVxVmdIZ5rwJ/1BLBJ0U=,tag:4i85uA7/ER7kinupHcp+2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVzRqaHRLSHFMUmJDNVlt
            cjV3QWZ1bTlLVlFCUHVZQkNPNWhVOU1QelM0CjFPZVo3S1ZhcW1YMEhkd25HaktD
            bUFRWEl3akhMNGtEK29XeENIS1l5ZlkKLS0tIGgzem94bVl3c1JsNGwwT3ZjTFBJ
            dTd4S3dwbkVMOHNkcDJHQVBsYVRDWHMKDkkcpeYWlh5CetEkiqHq/46w8XRSIBAN
            dF6cmhhwWWAnVI1r5vu9MJ9JVA6lveBVomWlx90NPnh6iElhMRk80g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-30T11:49:43Z"
    mac: ENC[AES256_GCM,data:mUBN9viLy3WR7ZTVgbzINM+oF3MPn/PeNO+ENu2OnNrWNuYs9jSMJHw4UPvHOjjzVGq8FjMyQBWillFfXvQ1azEkNeO1Lqc0Nx88uPkkVLzYw9JtjfTXL0PXyWI1dpa2tRhqQYXsqIpGyJch9/Zrwhklxnnpx5mhIzUASvBZvxY=,iv:P35LHHN6B74BWSPO04k/EXPgoKd86kxgP5j8ayOQ7qc=,tag:JRxx7+A6zE6q/KPcVbEjrw==,type:str]
    version: 3.13.3
