apiVersion: v1
kind: Secret
metadata:
    name: glance
    namespace: dashboard
stringData:
    TRUENAS_PROXY_HOST: ENC[AES256_GCM,data:k59KiH7et5vGF5iiwI8FLHrvwUj1,iv:Ycw5eTMCmAloEi74ib1LjOjWps6KXyyvXroxt8YuQ0A=,tag:+WWWZLXQk0AcOZ1fR8a3PQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGhlWDVGSzFOOVQvUHgv
            Mks0VlRESzdlSjRGOU9XQVpya0ZGbkxVUUdZCnppRklrTGcvamxKY3MrSXpsc2Vx
            N2wveW1CQUdDZUV5QVhtR2VPMExwMWcKLS0tIERMdzZ4U3Evb2Q3c0NvM09sQ3U2
            NW52dnFwaml4ODJXOUtwTUpjVnBwdmcKE3PatNxagxJ+hXU2zBEhXYzSs/m48Wjy
            kLM13sDe5Mas4RE5cWeWGXwMhPrAeACyuGOLWmgyFSoCJUtVljA+EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fcayjcsauny5czgwvyauqqqd4aa2kg3v7ghlvx6kjwqnz0luc9mq23famu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T11:26:30Z"
    mac: ENC[AES256_GCM,data:AI/COnn9nylAFghTiN9SRob5ehCCFjzV18g+YssjQiKfLG+IO5rU2xvasQs15U2J4IsSOLkRlLSsRsv0POXEOb37zffeBEZsafIFfrcCN9hWWPfva4IFJG/zukRdZp9ii5KgsjgtIDzmKo4a/+owKdKPRkKb5sBhTfWizVxBK7I=,iv:9VFpbiHiXS2umE2/aBlyIn5wjbnr6mWoYbvT/YYor5c=,tag:5/Az8ahO4ISE7kofQQU5fg==,type:str]
    version: 3.13.2
---
apiVersion: v1
kind: Secret
metadata:
    name: glance-truenas-proxy
    namespace: dashboard
stringData:
    TRUENAS_HOST: ENC[AES256_GCM,data:QnCBY9R7f2PM,iv:SkyjQPai5L9p5Ks5IVXWuY6vLDxYNvPQu+HBnNwPfUE=,tag:txGGDF94dAjoPiBd0/Mo3A==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:rFDMMi3VmjjAbgoD5dBjCQTacPQsPeF5SZNx5yd4oTha4e+AGrQD6OUIgI8+G8swrFiGssdOpaCv0izXZLKq6Aio,iv:QaZ0h1SUUwlFPDiuUdZr+cJVCzGoLOfsQzjHEQqYjI8=,tag:5/h/crLRFFLjoKHFgWo7Sg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVGhlWDVGSzFOOVQvUHgv
            Mks0VlRESzdlSjRGOU9XQVpya0ZGbkxVUUdZCnppRklrTGcvamxKY3MrSXpsc2Vx
            N2wveW1CQUdDZUV5QVhtR2VPMExwMWcKLS0tIERMdzZ4U3Evb2Q3c0NvM09sQ3U2
            NW52dnFwaml4ODJXOUtwTUpjVnBwdmcKE3PatNxagxJ+hXU2zBEhXYzSs/m48Wjy
            kLM13sDe5Mas4RE5cWeWGXwMhPrAeACyuGOLWmgyFSoCJUtVljA+EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fcayjcsauny5czgwvyauqqqd4aa2kg3v7ghlvx6kjwqnz0luc9mq23famu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-02T11:26:30Z"
    mac: ENC[AES256_GCM,data:AI/COnn9nylAFghTiN9SRob5ehCCFjzV18g+YssjQiKfLG+IO5rU2xvasQs15U2J4IsSOLkRlLSsRsv0POXEOb37zffeBEZsafIFfrcCN9hWWPfva4IFJG/zukRdZp9ii5KgsjgtIDzmKo4a/+owKdKPRkKb5sBhTfWizVxBK7I=,iv:9VFpbiHiXS2umE2/aBlyIn5wjbnr6mWoYbvT/YYor5c=,tag:5/Az8ahO4ISE7kofQQU5fg==,type:str]
    version: 3.13.2
