apiVersion: v1
kind: Secret
metadata:
    name: glance
    namespace: dashboard
stringData:
    TRUENAS_HOST: ENC[AES256_GCM,data:YSIIGlosjAK4xj4yKtlQ7w==,iv:CNHcGPZAsxp7thPcxVYdRtjm8qTmfOvGmGMsxDVQ/o4=,tag:2x0bw8gn+uVXoZkHiEI3+A==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:8qH98WHeLYVWGJbfxw7S1vY/vYjz87Sd5QdvnbztQV2coh9vwI+3hbQHCMXt4hVQebRq1V8wf6aA480aly9Navhb,iv:JtliW8H5E+KPoRHd21mxhWIcmlDddxbqYk0c0ZLRPjI=,tag:68H/Ftp+cJ+EXjnRPEyLJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YVBabUdSMGVkTW9Ic2Rm
            WXRHeHlVYVJ3QVdNUDN5Q1NIRmVVMWpXRTJjClQ4T2ZNQkd6c2JhaWVTbnJjeXdt
            eTVTV01tcjhubXR6aDE4RVV6amVWM0EKLS0tIE9qTC9aa1hSS3Q2SWNKb1hhcUIz
            bUIwSU45T2YvYVZQUmtndG9SVVNVeW8K8SjPy4e0uWToNrIJL96Wp7rqjiXCgek9
            FX+OQrML4SjDV//WcmE7jNLKc8DZJ7OEto5u/u3Iw5deJkJuQXxjAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fcayjcsauny5czgwvyauqqqd4aa2kg3v7ghlvx6kjwqnz0luc9mq23famu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-06T13:28:53Z"
    mac: ENC[AES256_GCM,data:V5GGkpjL3Zw8pMZhDIO6RB9i/4XLeukw611PEKSsWegFVsc5x/FRZxj9OeKwT9oaZ6QUnSjx1IVBApYkNz0obc90j40Hk4G22pA7eNnlsGUmpYz0fI1Sf+JsbgaQbBQoo6Fb61Usjv/SV7jqH5TDyRPDeESgLSqFJ/Dp7WnYmX0=,iv:DXdk8ULQfVgBziZ8ZTwHkfOPYstRFtjZ+aAEaaK1zYs=,tag:ZHcgU8rPPSGdocseuVikww==,type:str]
    version: 3.13.1
