apiVersion: v1
kind: Secret
metadata:
    name: glance
    namespace: dashboard
stringData:
    TRUENAS_PROXY_HOST: ENC[AES256_GCM,data:mZ/sOP9zG1j1m/+dn9ByP/AljcIP,iv:Kec/KLteEjcCWoESFjoJuf3ctWW3YOFf16liVMzoHT0=,tag:/bACPIfvqvRwMqb+Lz8D0Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWlU2c2tWVlp6NGp2SG9x
            S1kvRk41UURGQUJyTTAxdGtDRSt5VHQzTlFrCmVVaG0vVnVvQnFRTDdzUXJRK2N3
            U3dHWWMyaGxOVWkyMDMxSGJaQnFBUG8KLS0tIGU2Qy9pYjczWDR4TjAraEdGenEy
            MXY2Z0pGR01HcXBNTCtYUmt5eFU0VWsKAmcU9N2Y57sY2IFySzT5/lmFvYHsXYGd
            83rynRuU3qbncKU3FffJ0jCpz3T/reGOB2XjgXMg7CwX42P4Y235gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T10:52:51Z"
    mac: ENC[AES256_GCM,data:IWDK7ZVbA/q7Q334u+JnbqKqBYplgFEA4+PzarYWiYn8sFAyv0euQIGGFD19Ix/yUXMxio9u6DTyZ2fHdnb0YKVtsZAxFiCEUXJIi7891EQVuO11VpXesZR2hsGnp+WNMjUrge60PIpLvMD7TW1D8HOYLPGB5LcrqvfDTScubtI=,iv:xSYxl4GqSVJtG3DSIMIvIBgKun4+l1D/rV76oRBvuCk=,tag:ZfM3OKvoSBiuzY56A4zG8w==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: glance-truenas-proxy
    namespace: dashboard
stringData:
    TRUENAS_HOST: ENC[AES256_GCM,data:uddf4EgH38biv022tL6hdQ==,iv:MYq5xXoYEiBE4oor+blNQOxBKPcF00MAISlq3Jk33rA=,tag:ioxN8LCywdcx4nKGSl9DpA==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:aWm//pKhL9Aui2UdRtn8RNeJVc6KBI8did6KNXyTdplsWe3QA+y6Zq9mG0ZHVJU3VF5Mb1TzKDkKD7bAwPg/xwqk,iv:01jw2L+spCHFA0OOkokvaWKWoHPKVpouq9mFmQf9Ubg=,tag:qDJzq6dbmkrlOIrFnlfAjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxWlU2c2tWVlp6NGp2SG9x
            S1kvRk41UURGQUJyTTAxdGtDRSt5VHQzTlFrCmVVaG0vVnVvQnFRTDdzUXJRK2N3
            U3dHWWMyaGxOVWkyMDMxSGJaQnFBUG8KLS0tIGU2Qy9pYjczWDR4TjAraEdGenEy
            MXY2Z0pGR01HcXBNTCtYUmt5eFU0VWsKAmcU9N2Y57sY2IFySzT5/lmFvYHsXYGd
            83rynRuU3qbncKU3FffJ0jCpz3T/reGOB2XjgXMg7CwX42P4Y235gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T10:52:51Z"
    mac: ENC[AES256_GCM,data:IWDK7ZVbA/q7Q334u+JnbqKqBYplgFEA4+PzarYWiYn8sFAyv0euQIGGFD19Ix/yUXMxio9u6DTyZ2fHdnb0YKVtsZAxFiCEUXJIi7891EQVuO11VpXesZR2hsGnp+WNMjUrge60PIpLvMD7TW1D8HOYLPGB5LcrqvfDTScubtI=,iv:xSYxl4GqSVJtG3DSIMIvIBgKun4+l1D/rV76oRBvuCk=,tag:ZfM3OKvoSBiuzY56A4zG8w==,type:str]
    version: 3.13.3
