---
apiVersion: v1
kind: Namespace
metadata:
  name: livebook
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: livebook-truenas-pvc
  namespace: livebook
  annotations:
    storageClassName: "nfs-csi"
  labels:
    app: livebook
spec:
  storageClassName: nfs-csi
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---