---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: livebook-secret
  namespace: livebook
spec:
  encryptedData:
    LIVEBOOK_PASSWORD: AgAN6VvvKMR877sUGOsnq0f5AoA6aBGAekg83SgijFCZ4PcnFWDA/GCXuebjhSyl5Dy+jIxT7/23iOVug74i4zdTxUSDpSxfru343Yeu5DCJMmXn1ft6vQkHBEdwwaOSEyEziU/i0iVW1Yjbt+9vLUwwPqftyfv6fPFblTO6Wu2WvFPAIRZ+DuKCwU2vrwBYx8eDMTJFFl2UnOK3RjwzBJgpHjzPBKiZLEGkMdqwwk6QQxAzYgR85oYnXBlQ4jDRYKRnPx6qUblxTIkCpuasJON69C+wXnU3lHl6QKDHmfmYFkJnDaij9tHex69VPpAhvnQauuM+AjO2D9BkiUp5gm/rIUGINEhvmvdD8UtaFlxCpEs3W8OcNJL2KJfB3YycvUP9JxlDYFH11l4CdLzGQ3ptBE1VxCCzZDwLmqEZds1+9+/++fLGr7iayjy3jpHPDYvDExDhyWQEjrhC1eaJ8bpuWIgwPfjoFuhXaooPDvZoBmgBNkXRbRJVD3Rp0yIOMnEuj4nakBmGBWVKT4TXEJWPpEMpkoLzRvpcjRh8gFDY+EP61y/1Yrsgey5bATIefcUzjvTJU72bPC2swwcDZgMt4PO+ifINcuwVqm8a3bMkOYD6gw82hS6gjMg5EHbdJ7aqeasdNu6s8XYQ2soMaMHCjtDwPysFKbqVslRg12bgMZLPSAv2vjWjsrUTvIQ3J/K6Zl3shDGOMCdcYCqh3Dfbr6F8Qqj4x/TJaa8hHX8=
  template:
    metadata:
      creationTimestamp: null
      name: livebook-secret
      namespace: livebook
    type: Opaque
---