apiVersion: v1
kind: Service
metadata:
  name: pocketid-egress
  namespace: auth
  annotations:
    tailscale.com/tailnet-fqdn: "auth.hyrax-ghoul.ts.net"
spec:
  type: ExternalName
  externalName: placeholder
  ports:
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP