apiVersion: v1
kind: Secret
metadata:
    name: pocketid
    namespace: auth
stringData:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:klxvUo3DIuay342pjC1V2Uxf62L1IsWzQSlciH6e5l0Fatr+SAefbHmjKAI=,iv:GI95poxyLJnS2RrvtlLMuNhHUkpYOstmGkhOtmnXHLQ=,tag:ODNIpdlaN2z9oOy4mY6txg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjdm5OQ3dRdjJibmVTMU5Y
            dEEzR1hBME44aWxQdmkrbDhCR05XbDg5UkJVClBHUmtXQXVmVG0vb0NtYmtDODNl
            aTkwSGFGZWpjZzEyNDZXOGtJOENnSEEKLS0tIEErSHJUcWlmSXJsZ0xqeTFQc256
            Ti84Q0lReDh4Tlp2SmVSM3dGMDdkd0kK2yGA0WlVK2YhWQsToqbOvDiPY3RqqZxl
            DoRuCfpl279gZR6Quo29LC9JoIoV0HBuTZ4UY5oKLYzimMhge9edSQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1eps788r7kt7c57svnly95jmq4nk2lvuzdsjnfkdyqxq7kajlv5psr6z62c
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T08:16:26Z"
    mac: ENC[AES256_GCM,data:y/39LTABqpjlDO1rf1c3PhYs2Mx5Kl7niKMVxJeoJ5FRD57NVOFGc4DBouuCTpvbUbVDIHsjEbWvtwXvJC60xtjKDLQCzd1SOqG0UMUTXohlczmuFz0dn4ldW27W1znqMNWFx8UEOYPLQG4luWCppAbL74yvA4gOeDoxv3uCLfg=,iv:mrMWYSWKdfYzj/DSVN9SH2DvUghjW4Gg93TVlERHuzY=,tag:yIbagJI/Q76HSwaUdCj4tw==,type:str]
    version: 3.13.3
